# Generated by Django 4.2 on 2023-05-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_contract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
