# Generated by Django 4.2 on 2023-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_client_datecreated_alter_client_dateupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
