# Generated by Django 4.2 on 2023-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_contract_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='dateUpdated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
