# Generated by Django 4.2 on 2023-05-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_client_dateupdated'),
    ]

    operations = [
    ]
