# Generated by Django 4.2 on 2023-05-05 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20230505_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dateUpdated',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
