# Generated by Django 4.2 on 2023-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_alter_event_support_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventStatus',
            field=models.CharField(choices=[('1', 'Booked'), ('2', 'In progress'), ('3', 'Done')], default='1', max_length=10),
        ),
    ]
