# Generated by Django 4.2 on 2023-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
