# Generated by Django 4.2 on 2023-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vente', 'Vente'), ('support', 'Support'), ('gestion', 'Gestion')], error_messages={'invalid_choice': "Le rôle choisi est invalide. Les rôles disponibles sont : ['Vente', 'Support', 'Gestion']"}, max_length=10),
        ),
    ]
