# Generated by Django 4.2 on 2023-05-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vente', 'Vente'), ('support', 'Support'), ('gestion', 'Gestion')], error_messages={'invalid_choice': "Le rôle choisi est invalide. Les rôles disponibles sont : ['Vente', 'Support', 'Gestion']"}, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
