# Generated by Django 4.2 on 2023-05-17 08:42
from django.db import migrations
from sales.permissions import assign_group_permissions


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(assign_group_permissions, reverse_code=migrations.RunPython.noop),
    ]
