# Generated by Django 4.2 on 2023-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vente', 'Vente'), ('support', 'Support')], error_messages={'invalid_choice': "Le rôle choisi est invalide. Les rôles disponibles sont : ['Vente', 'Support']"}, max_length=10),
        ),
    ]
