# Generated by Django 4.2 on 2023-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventStatus',
            field=models.CharField(choices=[('1', 'Booked'), ('2', 'In progress'), ('3', 'Done')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
