# Generated by Django 4.2 on 2023-05-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_client', to='sales.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateUpdated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='dateUpdated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='paymentDue',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateUpdated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventStatus',
            field=models.CharField(choices=[('1', 'Booked'), ('2', 'In progress'), ('3', 'Done')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
