# Generated by Django 4.2 on 2023-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_client_dateupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
    ]
