# Generated by Django 4.2 on 2023-05-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_add_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
