# Generated by Django 4.2 on 2023-05-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
