# Generated by Django 4.2 on 2023-05-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='paymentDue',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
