# Generated by Django 4.2 on 2023-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_event_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
