# Generated by Django 4.2 on 2023-05-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_alter_event_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
